#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "matplotlib>=3.7",
# ]
# ///
import argparse
import csv
import math
import os
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot windowed cache hit rates from cmd/windowed_hitrate CSV output."
    )
    parser.add_argument("--input", required=True, help="Input CSV generated by scripts/windowed_hitrate")
    parser.add_argument("--output-dir", default=None, help="Output directory; default is input CSV directory")
    parser.add_argument("--output-prefix", default=None, help="Output file prefix; default is input stem")
    parser.add_argument("--window-sizes", default=None, help="Optional comma-separated window sizes to plot")
    parser.add_argument("--ymin", type=float, default=None, help="Y-axis minimum; default auto-zooms")
    parser.add_argument("--ymax", type=float, default=100.0, help="Y-axis maximum")
    parser.add_argument("--title", default=None, help="Plot title prefix")
    return parser.parse_args()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def parse_window_filter(raw: str | None) -> set[int] | None:
    if not raw:
        return None
    values = set()
    for part in raw.split(","):
        part = part.strip()
        if part:
            values.add(int(part))
    return values


def group_rows(rows: list[dict[str, str]], window_filter: set[int] | None):
    grouped: dict[int, dict[str, list[tuple[int, float]]]] = defaultdict(lambda: defaultdict(list))
    trace_name = ""
    for row in rows:
        window_size = int(row["window_size"])
        if window_filter is not None and window_size not in window_filter:
            continue
        label = row["config_label"]
        x_value = int(row["end_packet"])
        y_value = float(row["hit_rate_pct"])
        grouped[window_size][label].append((x_value, y_value))
        trace_name = row.get("trace_file_name", trace_name)
    for series in grouped.values():
        for points in series.values():
            points.sort(key=lambda item: item[0])
    return grouped, trace_name


def config_style(label: str) -> dict[str, object]:
    if label.startswith("MP"):
        return {"color": "#7B3294", "linestyle": "-", "marker": ""}
    if "ideal" in label.lower():
        return {"color": "#E66101", "linestyle": "--", "marker": ""}
    if "index21" in label.lower():
        return {"color": "#1F78B4", "linestyle": "-", "marker": ""}
    return {"linestyle": "-", "marker": ""}


def auto_ymin(series: dict[str, list[tuple[int, float]]], explicit: float | None) -> float:
    if explicit is not None:
        return explicit
    values = [point[1] for points in series.values() for point in points]
    if not values:
        return 0.0
    minimum = min(values)
    return max(0.0, math.floor((minimum - 1.0) / 5.0) * 5.0)


def format_window(window_size: int) -> str:
    if window_size % 1_000_000 == 0:
        return f"{window_size // 1_000_000}M"
    if window_size % 1_000 == 0:
        return f"{window_size // 1_000}K"
    return str(window_size)


def plot_one(
    series: dict[str, list[tuple[int, float]]],
    window_size: int,
    output_path: Path,
    trace_name: str,
    title_prefix: str | None,
    ymin: float | None,
    ymax: float,
) -> None:
    fig, ax = plt.subplots(figsize=(12, 6.5))
    for label in sorted(series):
        points = series[label]
        if not points:
            continue
        x_values = [x / 1_000_000 for x, _ in points]
        y_values = [y for _, y in points]
        ax.plot(x_values, y_values, linewidth=1.9, label=label, **config_style(label))

    title = title_prefix or "Windowed Hit Rate"
    if trace_name:
        title = f"{title}: {trace_name}"
    ax.set_title(f"{title} ({format_window(window_size)} packet windows)")
    ax.set_xlabel("Processed simulator packets (millions)")
    ax.set_ylabel("Hit rate in window (%)")
    ax.set_ylim(auto_ymin(series, ymin), ymax)
    ax.grid(True, alpha=0.25)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def plot_combined(
    grouped: dict[int, dict[str, list[tuple[int, float]]]],
    output_path: Path,
    trace_name: str,
    title_prefix: str | None,
    ymin: float | None,
    ymax: float,
) -> None:
    window_sizes = sorted(grouped)
    fig, axes = plt.subplots(len(window_sizes), 1, figsize=(12, 4.2 * len(window_sizes)), sharex=False)
    if len(window_sizes) == 1:
        axes = [axes]

    for ax, window_size in zip(axes, window_sizes):
        series = grouped[window_size]
        for label in sorted(series):
            points = series[label]
            if not points:
                continue
            ax.plot(
                [x / 1_000_000 for x, _ in points],
                [y for _, y in points],
                linewidth=1.7,
                label=label,
                **config_style(label),
            )
        ax.set_title(f"{format_window(window_size)} packet windows")
        ax.set_xlabel("Processed simulator packets (millions)")
        ax.set_ylabel("Hit rate (%)")
        ax.set_ylim(auto_ymin(series, ymin), ymax)
        ax.grid(True, alpha=0.25)
        ax.legend(frameon=False)

    title = title_prefix or "Windowed Hit Rate"
    if trace_name:
        title = f"{title}: {trace_name}"
    fig.suptitle(title, y=0.995)
    fig.tight_layout(rect=(0, 0, 1, 0.98))
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    rows = read_rows(input_path)
    if not rows:
        print(f"No rows found in {input_path}", file=sys.stderr)
        return 1

    grouped, trace_name = group_rows(rows, parse_window_filter(args.window_sizes))
    if not grouped:
        print("No plottable rows after applying filters.", file=sys.stderr)
        return 1

    output_dir = Path(args.output_dir) if args.output_dir else input_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    output_prefix = args.output_prefix or input_path.stem

    outputs: list[Path] = []
    for window_size, series in sorted(grouped.items()):
        output_path = output_dir / f"{output_prefix}_{format_window(window_size).lower()}.png"
        plot_one(series, window_size, output_path, trace_name, args.title, args.ymin, args.ymax)
        outputs.append(output_path)

    combined_path = output_dir / f"{output_prefix}_combined.png"
    plot_combined(grouped, combined_path, trace_name, args.title, args.ymin, args.ymax)
    outputs.append(combined_path)

    for output in outputs:
        print(f"Saved graph: {output}")
    return 0


if __name__ == "__main__":
    os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")
    raise SystemExit(main())
