#!/usr/bin/env python3
import argparse
import csv
import statistics
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write a Markdown summary for windowed hitrate CSVs.")
    parser.add_argument("--input", required=True, help="Input CSV generated by scripts/windowed_hitrate")
    parser.add_argument("--output", required=True, help="Output Markdown path")
    return parser.parse_args()


def pct(value: float) -> str:
    return f"{value:.6f}%"


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    with input_path.open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"no rows found: {input_path}")

    trace_name = rows[0].get("trace_file_name", "")
    trace_path = rows[0].get("trace_path", "")
    rule_name = rows[0].get("rule_file_name", "")
    mode = rows[0].get("window_mode", "warm")

    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["config_label"], row["window_size"])].append(row)

    lines = [
        f"# Windowed hit rate summary: {trace_name}",
        "",
        "## Input",
        "",
        f"- trace: `{trace_path}`",
        f"- rule: `{rule_name}`",
        f"- window mode: `{mode}`",
        f"- CSV: `{input_path}`",
        "",
        "## Interpretation",
        "",
    ]

    if mode == "cold":
        lines.extend(
            [
                "Each window is measured from an empty cache. For example, every 10K packet block is processed by a freshly initialized cache, then the cache is discarded before the next 10K block.",
                "",
                "`hit_rate_pct` is the hit rate inside that single cold-start window. `cumulative_hit_rate_pct` is the aggregate of those independent cold-start windows, not one continuous cache run.",
            ]
        )
    else:
        lines.extend(
            [
                "The cache is warmed continuously across the trace. `hit_rate_pct` is still per-window, but only the first window pays the full empty-cache penalty.",
                "",
                "`cumulative_hit_rate_pct` is the hit rate from packet 0 through the end of the current window for one continuous cache run.",
            ]
        )

    lines.extend(
        [
            "",
            "## Summary",
            "",
            "| config | window | rows | first | min | mean | max | last | final cumulative |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )

    def sort_key(item: tuple[tuple[str, str], list[dict[str, str]]]):
        (label, window_size), _ = item
        return (int(window_size), label)

    for (label, window_size), group_rows in sorted(grouped.items(), key=sort_key):
        group_rows.sort(key=lambda row: int(row["window_index"]))
        values = [float(row["hit_rate_pct"]) for row in group_rows]
        final = float(group_rows[-1]["cumulative_hit_rate_pct"])
        lines.append(
            "| {label} | {window} | {rows} | {first} | {minv} | {mean} | {maxv} | {last} | {final} |".format(
                label=label,
                window=window_size,
                rows=len(group_rows),
                first=pct(values[0]),
                minv=pct(min(values)),
                mean=pct(statistics.fmean(values)),
                maxv=pct(max(values)),
                last=pct(values[-1]),
                final=pct(final),
            )
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote summary: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
